### ISSUE TITLE
Fix logic to refer to input DOM event

### ISSUE THREAD

**Issue by jennyknuth** [nioinnovation/react-nuik#3]
Right now, with an uncontrolled component, the placeholder/label element does not stay above the bar when bar is filled. 

Refactor implementation using `input` DOM event https://developer.mozilla.org/en-US/docs/Web/Events/input.

**Comment by 32bitkid** [comment]
i think this is presently resolved?

**Comment by jennyknuth** [comment]
resolve with PR#5
